ansible_roles_path = '/data/roles'

Vagrant.configure('2') do |config|
  # configure vagrant-proxyconf plugin
  # If proxy is configured via ENV variables
  # then we configure vagrant to use proxy
  unless ENV['http_proxy'].nil?
    config.proxy.enabled  = true
    # set values from environmental variables
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['http_proxy']
    config.proxy.no_proxy = ENV['no_proxy']
  end

  config.vm.box = 'bento/centos-7.8'
  config.vm.synced_folder './', '/vagrant', mount_options: ['dmode=775,fmode=644']
  config.vm.network 'forwarded_port', guest: 80, host: 8080

  config.vm.provision "Set permissions to #{ansible_roles_path}",
                      type: :shell,
                      inline: "mkdir -vp #{ansible_roles_path} ;
                               chmod o+w #{ansible_roles_path}"

  # customisation for virtualbox
  config.vm.provider 'virtualbox' do |box|
    box.memory = 1024
  end

  # provision VM via bash
#  config.vm.provision 'shell', path: 'provision_me.sh'
  config.vm.provision 'ansible_local' do |ansible|
    ansible.install_mode = "pip3"
    ansible.galaxy_roles_path = ansible_roles_path
    ansible.playbook = "/vagrant/provision_me.yml"
    ansible.version = "2.9.27"
    ansible.verbose = 'v'
  end
end
