---
- name: Configure iptables
  template:
    src: "{{ iptables_provision__iptables_item }}.j2"
    dest: "/etc/sysconfig/{{ iptables_provision__iptables_item }}"
    force: true
    # it's commented because github actions do not allow use ip6
    # https://github.com/actions/virtual-environments/issues/668
    # validate: "/sbin/{{ game2048__iptables_item }}-restore --test %s"
    mode: 0644
    owner: root
    group: root
  loop:
    - iptables
    - ip6tables
  loop_control:
    loop_var: iptables_provision__iptables_item
  notify:
    - iptables_provision reload iptables
    - iptables_provision reload ip6tables
    - restart and enable iptables
    - restart and enable ip6tables