Vagrant.configure('2') do |config|
  unless ENV['http_proxy'].nil?
    config.proxy.enabled  = true
    # set values from environmental variables
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['http_proxy']
    config.proxy.no_proxy = ENV['no_proxy']
  end

  config.vm.synced_folder './', '/vagrant', mount_options: ['dmode=775,fmode=644']
  config.vm.box = 'bento/centos-7.8'
  config.vm.provider 'virtualbox' do |box|
    box.memory = 1024
  end

  config.vm.network 'forwarded_port', guest: 80, host: 8080
  # copy my pub key
#  config.vm.provision "shell" do |s|
#    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
#    s.inline = <<-SHELL
#      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
#      sudo echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
#    SHELL
#  end

  config.vm.provision 'ansible_local' do |ansible|
    ansible.playbook = '/vagrant/provision_me.yml'
    ansible.verbose = 'v'
    ansible.install_mode = "pip3"
    ansible.version = "2.9.27"
  end
end
