---
docker_user: vagrant
docker_software:
  - yum-utils 
  - device-mapper-persistent-data
  - lvm2
docker_compose_url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64