# install pip2 on centos
---
- name: "Download script for install"
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: ~/get-pip.py
    mode: u+x,g+x,o+x
  notify: 
    - install pip