---

- name: provision 2
  hosts: all
  vars:
    iptables_allowed_ports:
      - {protocol: tcp, port: 80}
      - {protocol: tcp, port: 443}
      - {protocol: udp, port: 161}
  roles:
    - role: install_molecule
