---
# handlers file for iptables_provision

- name: "Import custom module"
  import_role:
    name: apply_iptables_module

- name: iptables_provision reload iptables
  apply_iptables:
    name: iptables
    path: /etc/sysconfig/iptables

- name: iptables_provision reload ip6tables
  apply_iptables:
    name: ip6tables
    path: /etc/sysconfig/ip6tables

- name: restart and enable iptables
  systemd:
    name: iptables
    enabled: true
    state: restarted
    daemon_reload: true

- name: restart and enable ip6tables
  systemd:
    name: ip6tables
    enabled: true
    state: restarted
    daemon_reload: true